//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMQLCHDIENTHOAI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sp_1 {
            get {
                return ((string)(this["sp_1"]));
            }
            set {
                this["sp_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int cnThemTaiKhoan {
            get {
                return ((int)(this["cnThemTaiKhoan"]));
            }
            set {
                this["cnThemTaiKhoan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int cnXoaTaiKhoan {
            get {
                return ((int)(this["cnXoaTaiKhoan"]));
            }
            set {
                this["cnXoaTaiKhoan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int cnPhanQuyen {
            get {
                return ((int)(this["cnPhanQuyen"]));
            }
            set {
                this["cnPhanQuyen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int cnReset {
            get {
                return ((int)(this["cnReset"]));
            }
            set {
                this["cnReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int cnThemSuaXoaNhomQuyen {
            get {
                return ((int)(this["cnThemSuaXoaNhomQuyen"]));
            }
            set {
                this["cnThemSuaXoaNhomQuyen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int cnXemDSTaiKhoan {
            get {
                return ((int)(this["cnXemDSTaiKhoan"]));
            }
            set {
                this["cnXemDSTaiKhoan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int cnXemThongTinTaiKhoan {
            get {
                return ((int)(this["cnXemThongTinTaiKhoan"]));
            }
            set {
                this["cnXemThongTinTaiKhoan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int cnThemNV {
            get {
                return ((int)(this["cnThemNV"]));
            }
            set {
                this["cnThemNV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int cnXemDSNV {
            get {
                return ((int)(this["cnXemDSNV"]));
            }
            set {
                this["cnXemDSNV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int cnXemTTNV {
            get {
                return ((int)(this["cnXemTTNV"]));
            }
            set {
                this["cnXemTTNV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int cnCapNhatTTNV {
            get {
                return ((int)(this["cnCapNhatTTNV"]));
            }
            set {
                this["cnCapNhatTTNV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int cnTimNV {
            get {
                return ((int)(this["cnTimNV"]));
            }
            set {
                this["cnTimNV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int cnXoaNhanVien {
            get {
                return ((int)(this["cnXoaNhanVien"]));
            }
            set {
                this["cnXoaNhanVien"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int cnThemCV {
            get {
                return ((int)(this["cnThemCV"]));
            }
            set {
                this["cnThemCV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int cnXemDSCV {
            get {
                return ((int)(this["cnXemDSCV"]));
            }
            set {
                this["cnXemDSCV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int cnXemTTCV {
            get {
                return ((int)(this["cnXemTTCV"]));
            }
            set {
                this["cnXemTTCV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int cnXoaCV {
            get {
                return ((int)(this["cnXoaCV"]));
            }
            set {
                this["cnXoaCV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int cnCapNhTTCV {
            get {
                return ((int)(this["cnCapNhTTCV"]));
            }
            set {
                this["cnCapNhTTCV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int cnXuatDSNV {
            get {
                return ((int)(this["cnXuatDSNV"]));
            }
            set {
                this["cnXuatDSNV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int cnDSNCC {
            get {
                return ((int)(this["cnDSNCC"]));
            }
            set {
                this["cnDSNCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int cnXoaNCC {
            get {
                return ((int)(this["cnXoaNCC"]));
            }
            set {
                this["cnXoaNCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int cnThemNCC {
            get {
                return ((int)(this["cnThemNCC"]));
            }
            set {
                this["cnThemNCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int cnXemNCC {
            get {
                return ((int)(this["cnXemNCC"]));
            }
            set {
                this["cnXemNCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int cnXuatNCC {
            get {
                return ((int)(this["cnXuatNCC"]));
            }
            set {
                this["cnXuatNCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int cnCapNhatNCC {
            get {
                return ((int)(this["cnCapNhatNCC"]));
            }
            set {
                this["cnCapNhatNCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26")]
        public int cnThemLoai {
            get {
                return ((int)(this["cnThemLoai"]));
            }
            set {
                this["cnThemLoai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int cnSuaLoai {
            get {
                return ((int)(this["cnSuaLoai"]));
            }
            set {
                this["cnSuaLoai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28")]
        public int cnXoaLoai {
            get {
                return ((int)(this["cnXoaLoai"]));
            }
            set {
                this["cnXoaLoai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29")]
        public int cnXemLoai {
            get {
                return ((int)(this["cnXemLoai"]));
            }
            set {
                this["cnXemLoai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int cnThemDVT {
            get {
                return ((int)(this["cnThemDVT"]));
            }
            set {
                this["cnThemDVT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31")]
        public int cnSuaDVT {
            get {
                return ((int)(this["cnSuaDVT"]));
            }
            set {
                this["cnSuaDVT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int cnXoaDVT {
            get {
                return ((int)(this["cnXoaDVT"]));
            }
            set {
                this["cnXoaDVT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33")]
        public int cnXemDVt {
            get {
                return ((int)(this["cnXemDVt"]));
            }
            set {
                this["cnXemDVt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34")]
        public int cnThemBank {
            get {
                return ((int)(this["cnThemBank"]));
            }
            set {
                this["cnThemBank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int cnSuaBank {
            get {
                return ((int)(this["cnSuaBank"]));
            }
            set {
                this["cnSuaBank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public int cnXoaBank {
            get {
                return ((int)(this["cnXoaBank"]));
            }
            set {
                this["cnXoaBank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37")]
        public int cnXemBank {
            get {
                return ((int)(this["cnXemBank"]));
            }
            set {
                this["cnXemBank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38")]
        public int cnLapSold {
            get {
                return ((int)(this["cnLapSold"]));
            }
            set {
                this["cnLapSold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39")]
        public int cnCapNhatSold {
            get {
                return ((int)(this["cnCapNhatSold"]));
            }
            set {
                this["cnCapNhatSold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int cnXemDSSold {
            get {
                return ((int)(this["cnXemDSSold"]));
            }
            set {
                this["cnXemDSSold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41")]
        public int cnXemDetailSold {
            get {
                return ((int)(this["cnXemDetailSold"]));
            }
            set {
                this["cnXemDetailSold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42")]
        public int cnXuatSold {
            get {
                return ((int)(this["cnXuatSold"]));
            }
            set {
                this["cnXuatSold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43")]
        public int cnCapTTSold {
            get {
                return ((int)(this["cnCapTTSold"]));
            }
            set {
                this["cnCapTTSold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44")]
        public int cnLapChi {
            get {
                return ((int)(this["cnLapChi"]));
            }
            set {
                this["cnLapChi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int cnXemChi {
            get {
                return ((int)(this["cnXemChi"]));
            }
            set {
                this["cnXemChi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46")]
        public int cnLapBuy {
            get {
                return ((int)(this["cnLapBuy"]));
            }
            set {
                this["cnLapBuy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("47")]
        public int cnCapNhatBuy {
            get {
                return ((int)(this["cnCapNhatBuy"]));
            }
            set {
                this["cnCapNhatBuy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public int cnXemDSBuy {
            get {
                return ((int)(this["cnXemDSBuy"]));
            }
            set {
                this["cnXemDSBuy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49")]
        public int cnXemDetailBuy {
            get {
                return ((int)(this["cnXemDetailBuy"]));
            }
            set {
                this["cnXemDetailBuy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int cnXuatBuy {
            get {
                return ((int)(this["cnXuatBuy"]));
            }
            set {
                this["cnXuatBuy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51")]
        public int cnCapNhatTTBuy {
            get {
                return ((int)(this["cnCapNhatTTBuy"]));
            }
            set {
                this["cnCapNhatTTBuy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public int cnLapBH {
            get {
                return ((int)(this["cnLapBH"]));
            }
            set {
                this["cnLapBH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53")]
        public int cnCapNhatBH {
            get {
                return ((int)(this["cnCapNhatBH"]));
            }
            set {
                this["cnCapNhatBH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54")]
        public int cnXemDSBH {
            get {
                return ((int)(this["cnXemDSBH"]));
            }
            set {
                this["cnXemDSBH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int cnXemDetailBH {
            get {
                return ((int)(this["cnXemDetailBH"]));
            }
            set {
                this["cnXemDetailBH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56")]
        public int cnXuatBH {
            get {
                return ((int)(this["cnXuatBH"]));
            }
            set {
                this["cnXuatBH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57")]
        public int cnLapSC {
            get {
                return ((int)(this["cnLapSC"]));
            }
            set {
                this["cnLapSC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("58")]
        public int cnCapNhatSC {
            get {
                return ((int)(this["cnCapNhatSC"]));
            }
            set {
                this["cnCapNhatSC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("59")]
        public int cnXemDSSC {
            get {
                return ((int)(this["cnXemDSSC"]));
            }
            set {
                this["cnXemDSSC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int cnXemSC {
            get {
                return ((int)(this["cnXemSC"]));
            }
            set {
                this["cnXemSC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61")]
        public int cnXuatSC {
            get {
                return ((int)(this["cnXuatSC"]));
            }
            set {
                this["cnXuatSC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62")]
        public int cnThemTB {
            get {
                return ((int)(this["cnThemTB"]));
            }
            set {
                this["cnThemTB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("63")]
        public int cnCapNhatTB {
            get {
                return ((int)(this["cnCapNhatTB"]));
            }
            set {
                this["cnCapNhatTB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public int cnXoaTB {
            get {
                return ((int)(this["cnXoaTB"]));
            }
            set {
                this["cnXoaTB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int cnCapNhatSLTB {
            get {
                return ((int)(this["cnCapNhatSLTB"]));
            }
            set {
                this["cnCapNhatSLTB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66")]
        public int cnLapBG {
            get {
                return ((int)(this["cnLapBG"]));
            }
            set {
                this["cnLapBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("67")]
        public int cnCapNhatTK {
            get {
                return ((int)(this["cnCapNhatTK"]));
            }
            set {
                this["cnCapNhatTK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68")]
        public int cnThemPTGH {
            get {
                return ((int)(this["cnThemPTGH"]));
            }
            set {
                this["cnThemPTGH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("69")]
        public int cnCapNhatPTGH {
            get {
                return ((int)(this["cnCapNhatPTGH"]));
            }
            set {
                this["cnCapNhatPTGH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int cnXoaPTGH {
            get {
                return ((int)(this["cnXoaPTGH"]));
            }
            set {
                this["cnXoaPTGH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("71")]
        public int cnLapPBH {
            get {
                return ((int)(this["cnLapPBH"]));
            }
            set {
                this["cnLapPBH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("72")]
        public int cnXemDSPBH {
            get {
                return ((int)(this["cnXemDSPBH"]));
            }
            set {
                this["cnXemDSPBH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("73")]
        public int cnXemPBH {
            get {
                return ((int)(this["cnXemPBH"]));
            }
            set {
                this["cnXemPBH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("74")]
        public int cnThemKH {
            get {
                return ((int)(this["cnThemKH"]));
            }
            set {
                this["cnThemKH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int cnDSKH {
            get {
                return ((int)(this["cnDSKH"]));
            }
            set {
                this["cnDSKH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("76")]
        public int cnTTKH {
            get {
                return ((int)(this["cnTTKH"]));
            }
            set {
                this["cnTTKH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("77")]
        public int cnCapNhatKH {
            get {
                return ((int)(this["cnCapNhatKH"]));
            }
            set {
                this["cnCapNhatKH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("78")]
        public int cnXoaKH {
            get {
                return ((int)(this["cnXoaKH"]));
            }
            set {
                this["cnXoaKH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79")]
        public int cnXuatKh {
            get {
                return ((int)(this["cnXuatKh"]));
            }
            set {
                this["cnXuatKh"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NGUYENNHIPUKA;Initial Catalog=DATABASE_DT;Integrated Security=True")]
        public string DATABASE_DTConnectionString {
            get {
                return ((string)(this["DATABASE_DTConnectionString"]));
            }
        }
    }
}
